### ISSUE TITLE
Interested in sex toy interaction with your game?

### ISSUE THREAD

**Issue by qdot** [maldrasen/jadefire#67]
First off, congrats on your appearance on the Developers Swearing twitter bot. :) https://twitter.com/gitlost/status/945063795063513088

Anyways, since I'm not sure if the FA account I found with the same name is yours, I'll post as an issue, hoping you don't regard this as spam. :)

If you're interested in sex toy/hardware interaction with your game, check out https://github.com/metafetish/buttplug-js. I haven't tried bringing up our native node bluetooth core under electron yet, so it might take some work on our end, but if you're interested in integrating when you get to a good point for that, I'd be happy to discuss it more.

**Comment by maldrasen** [comment]
Hey thank you for the suggestion. I think it sounds like something with a lot of interesting possibilities. A few challenges too that I can think of, as the game is going to be turn based, if I send a command to a device, it might take some time before anther command can be sent. I'm thinking I have at least another year's worth of development too before I can even release a playable demo.

Until then though I can start to think of a few ways such devices can be worked into what I have now. The future state of the game will be a management RPG, where your player is managing a bar or brothel. I'm starting in on the most complicated part, the sex scene engine now. I have some sex toys implemented already, and some simple capacity for NPCs to use toys on the player. I think we could make that at least one of the integration points. 

Characters should also be able to act somewhat independently as well, and during the course of a game a character might tell you to put your butt plug in, maybe turn it on and off randomly for you over the course of the day.

But yes, ht FA account is also me, but this is probably the best place to contact me.

**Comment by qdot** [comment]
Ah, neat! Yeah, I was trying to glean information from commit messages, so this was a bit of a shot in the dark. Glad you weren't annoyed by it. :)

I like the management RPG idea! That sounds like it'll be really cool. I'm currently working on twine macros for our framework, just to see what we can do in the interactive fiction realm.

Anyways, feel free to @ me in issues if you've got any questions or want to play around with the API at some point, or we've got a discord server/telegram group if you're interested. We're only like 8 months into development ourselves, so everything is still rather rough. :)
